$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

function Get-U8([string]$p){ [System.IO.File]::ReadAllText($p, (New-Object System.Text.UTF8Encoding($false))) }
function Set-U8([string]$p,[string]$c){ [System.IO.File]::WriteAllText($p, $c, (New-Object System.Text.UTF8Encoding($false))) }

$yaml = Get-Content C:\Users\GWL\.dsh\.credentials.yaml -Raw
$key  = [regex]::Match($yaml, 'TOKENRHYTHM_API_KEY:\s*["'']?([^"'']+)').Groups[1].Value
$headers = @{ Authorization="Bearer $key"; 'Content-Type'='application/json' }
$uri = 'https://tokenrhythm.studio/v1/chat/completions'

function Invoke-QC([string]$label,[string]$prompt,[string]$imagePath){
    $img=[Convert]::ToBase64String([IO.File]::ReadAllBytes($imagePath))
    $dataUrl='data:image/png;base64,'+$img
    $call=0
    while($true){
        $call++
        $body = @{ model='qwen3.7-flash'; messages=@(@{role='user';content=@(@{type='text';text=$prompt},@{type='image_url';image_url=@{url=$dataUrl}})}); max_tokens=3000 } | ConvertTo-Json -Depth 8
        $byteBody=[System.Text.Encoding]::UTF8.GetBytes($body)
        try{
            $r = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $byteBody -TimeoutSec 240
            $txt=$r.choices[0].message.content
            if([string]::IsNullOrWhiteSpace($txt)){ $txt=$r.choices[0].message.reasoning_content }
            Write-Output "  -> $label success attempt $call"
            return $txt
        }catch{
            $code=$null
            if($_.Exception.Response -and $_.Exception.Response.StatusCode){ $code=[int]$_.Exception.Response.StatusCode }
            $isTimeout=$_.Exception.Message -match 'timed out|timeout|terminated'
            $detail=''
            if($_.ErrorDetails.Message){ $detail=$_.ErrorDetails.Message }
            Write-Output "  -> $label attempt $call FAILED HTTP=$code $($_.Exception.Message) $detail"
            if($call -ge 5){ Write-Output "  -> $label GAVE UP"; return "QC_ERROR: $($_.Exception.Message) $detail" }
            if($code -eq 429 -or $isTimeout){ Write-Output '  backoff 15s'; Start-Sleep -Seconds 15; continue }
            return "QC_ERROR: $($_.Exception.Message) $detail"
        }
    }
}

$dir='C:\Users\GWL\Desktop\itwillclaude\games\wuxian-horror-ch1\tools\design'
$imgA="$dir\raw_enemy\hunter.png"
$imgB='C:\Users\GWL\Desktop\itwillclaude\games\wuxian-horror-ch1\server-rs\ui\assets\img\enemy_hunter.png'
$imgC="$dir\preview_enemy\preview_enemy_hunter.png"

$pA = Get-U8 "$dir\qc_prompt_A.txt"
$pB = Get-U8 "$dir\qc_prompt_B.txt"
$pC = Get-U8 "$dir\qc_prompt_C.txt"

$hdr = '# Monster Hunter QA (qwen3.7-flash)'
$sA="";$sB="";$sC=""

Write-Output "--- A ---"
$sA = Invoke-QC -label 'A' -prompt $pA -imagePath $imgA
Set-U8 "$dir\qc_result_A_raw.md"  ("$hdr`n`n# A. raw_detail (hunter.png 768x1024 black-bg)`n`n## verdict & reasons`n`n" + $sA + "`n")

Write-Output "--- B ---"
$sB = Invoke-QC -label 'B' -prompt $pB -imagePath $imgB
Set-U8 "$dir\qc_result_B_cutout.md" ("$hdr`n`n# B. cutout (enemy_hunter.png transparent-bg)`n`n## verdict & reasons`n`n" + $sB + "`n")

Write-Output "--- C ---"
$sC = Invoke-QC -label 'C' -prompt $pC -imagePath $imgC
Set-U8 "$dir\qc_result_C_preview.md" ("$hdr`n`n# C. preview (preview_enemy_hunter.png chessboard 384x512)`n`n## verdict & reasons`n`n" + $sC + "`n")

# summary file (with context, in English + suggestion)
$sum = @"
# Monster Hunter 猎杀者 QC summary (r3) - qwen3.7-flash

> Role: visual art QA via qwen3.7-flash. Images were graded one-per-call.
> Asset: Hello Horrific / 无限恐怖 monster "Hunter" (skinned muscle monster, broad shoulders / thick chest / sealed solid trunk / prominent muscle volume / slightly crouched threatening pose / white bone spikes / optional no tail / full body).

## A. raw_detail (hunter.png)  -- original full-body standing art, pure black bg
$sA

## B. cutout (enemy_hunter.png) -- transparent-background cutout
$sB

## C. preview (preview_enemy_hunter.png) -- chessboard composite 384x512
$sC

---
*Generated by qwen3.7-flash vision QA. WRITE ONLY, no cherry-picking.*
"@
Set-U8 "$dir\qc_hunter_r3.md" $sum
Write-Output "ALL DONE"